### ISSUE TITLE
Hardcoded use_cuda to True for openmpi-cifar10-resnet20-all-reduce

### ISSUE THREAD

**Issue by akantak** [mlbench/mlbench-benchmarks#10]
In latest commit (https://github.com/mlbench/mlbench-benchmarks/commit/43d700c7f7166644fde313ed75583c34edce556a#diff-e482240eb6fb679b324d992a5ca5bda6R69) on develop there was a bug introduced which hardcodes use_cuda variable in one place to True, which makes unable to run without CUDA. 

You can see it here:
https://github.com/mlbench/mlbench-benchmarks/blob/develop/pytorch/imagerecognition/openmpi-cifar10-resnet20-all-reduce/main.py#L69

**Comment by Panaetius** [comment]
Thanks for the info, good catch.
Fixing it now.
