### ISSUE TITLE
No unit tests

### ISSUE THREAD

**Issue by cgrigis** [mlbench/mlbench-benchmarks#40]
I could not find unit tests for the various benchmark implementations.

**Comment by Panaetius** [comment]
You mean for the `main.py` files in the benchmarks?

**Comment by cgrigis** [comment]
Yes, exactly. Does it make sense to unit-test them?

**Comment by martinjaggi** [comment]
any update on this? we've added tests on several more fine-grained parts now, but not on the end-to-end benchmark runs. the success of the benchmark itself as in terms of accuracy reached (say of the light goal) serves as the ultimate test. both in the single node and distributed case.

can i close this?

**Comment by cgrigis** [comment]
If there is no added value with unit tests, that can definitely be closed as far as I am concerned.

**Comment by ehoelzl** [comment]
Closing this issue as such tests have no added value (and can hardly be automated)
