### ISSUE TITLE
Create light version of the base image for development

### ISSUE THREAD

**Issue by mmilenkoski** [mlbench/mlbench-benchmarks#43]
We should add a light version of the base image with only the essential libraries. This will be useful to speed up local development and testing. For example, we could exclude cuda and openmpi. Are there any non-essential imports that we could exclude and would significantly reduce the image size?

**Comment by ehoelzl** [comment]
For that, we could simply use the base image of pytorch `pytorch/pytorch:1.5-cuda10.1-cudnn7-devel`
