### ISSUE TITLE
can it be used in other servers? such as: my machine,because the document is described by gcloud

### ISSUE THREAD

**Issue by muzhailong** [mlbench/mlbench-benchmarks#66]

**Comment by ehoelzl** [comment]
You can use `kind` to deploy on a local cluster if needed https://mlbench.readthedocs.io/en/latest/installation.html#kubernetes-in-docker-kind

**Comment by muzhailong** [comment]
> You can use `kind` to deploy on a local cluster if needed https://mlbench.readthedocs.io/en/latest/installation.html#kubernetes-in-docker-kind

thank you very much，but we want use it ，but we want use many machines to test allreduce。The link you give me may be not  ok，you have other way to solve it? thank you very very very much!

**Comment by ehoelzl** [comment]
Could you please describe your architecture ? we currently support deployment on GCP and AWS, but you can always tweak the deployment to work on any kubernetes cluster using `helm` https://mlbench.readthedocs.io/en/latest/installation.html#manual-helm-chart-deployment-optional
